class_name MainLocalization
extends RefCounted

## 사용자에게 표시되는 한국어 원문을 보존하면서 해외 배포용 영어 문구를 제공한다.
## 한국어 locale에서는 원문을 그대로 사용하고 영어 locale에서는 이 catalog를 적용한다.

const ENGLISH: String = "en"
const KOREAN: String = "ko"
const SUPPORTED_LANGUAGES: Array[String] = [ENGLISH, KOREAN]

const ENGLISH_MESSAGES: Dictionary = {
	# Main menu and navigation.
	"격투 액션 × 낙하 블록": "ARCADE COMBAT × FALLING BLOCKS",
	"블록파이터": "BLOCK\nFIGHTER",
	"낙하 블록 위에서 펼쳐지는 격투 액션": "Fight your way across a battlefield of falling blocks",
	"게임 설명": "HOW TO PLAY",
	"↑ ↓ 선택    Z 확인": "↑ ↓ Navigate    Z Confirm",
	"클리어한 스테이지의 별은 다음 도전에 이어집니다": "Stars earned in cleared stages carry over to future runs.",
	"별 0개": "0 Stars",
	"별 %d개": "%d Stars",
	"캐릭터 선택": "CHARACTER SELECT",
	"블록 깨러 가기": "ENTER STAGE",
	"상점": "UPGRADES",
	"메인으로": "MAIN MENU",
	"스테이지 선택으로": "STAGE SELECT",
	"입장 가능": "READY",
	"잠김": "LOCKED",
	"상점 선택": "UPGRADES",
	"전역 패시브 강화": "PERMANENT UPGRADES",
	"아이콘을 선택하면 아래에서 세부 정보를 확인할 수 있습니다.": "Select an upgrade to view its details below.",
	"선택 후 Z로 강화": "Select, then press Z to upgrade",
	"패시브 초기화": "RESET UPGRADES",
	"그림과 화살표를 따라 기능을 익혀보세요": "Follow the animated examples to learn the essentials.",
	"← 이전": "← PREVIOUS",
	"다음 →": "NEXT →",
	"키 설정과 사운드 크기를 조절합니다": "Customize controls, audio, and language.",
	"이동·액션·시스템 키를\n원하는 키로 변경합니다.": "Remap movement, combat,\nand system controls.",
	"키 설정 열기": "OPEN CONTROLS",
	"BGM과 효과음의 크기를\n각각 조절합니다.": "Adjust music and sound\neffect volume separately.",
	"볼륨 설정 열기": "OPEN AUDIO",
	"진행 데이터 초기화": "RESET PROGRESS",
	"스테이지 해금과 별 재화를 지웁니다.": "Erase stage unlocks, stars, and upgrades.",
	"진행 상황 삭제": "DELETE PROGRESS",
	"버튼을 누른 뒤 새 키를 입력하세요": "Select a binding, then press the new key.",
	"동작": "ACTION",
	"주 키": "PRIMARY",
	"보조 키": "SECONDARY",
	"지우기": "CLEAR",
	"기본값 복원": "RESTORE DEFAULTS",
	"OPTION으로": "BACK TO OPTIONS",
	"향후 추가되는 음악과 효과음에도 설정이 유지됩니다": "These levels also apply to newly added music and effects.",
	"0%는 음소거입니다. 음악은 BGM 버스,\n효과음은 SFX 버스를 지정하면 이 설정을 사용합니다.": "0% mutes the channel. Music uses the BGM channel;\nsound effects use the SFX channel.",
	"새 키 입력": "PRESS A NEW KEY",
	"취소": "CANCEL",
	"안내": "NOTICE",
	"확인": "OK",
	"진행 데이터를 삭제할까요?": "Delete all progress?",
	"스테이지 해금과 별 재화가 초기화됩니다.": "Stage unlocks, stars, and upgrades will be reset.",
	"삭제": "DELETE",
	"패시브를 초기화할까요?": "Reset all upgrades?",
	"투자한 별을 모두 돌려받습니다.": "All spent stars will be refunded.",
	"초기화": "RESET",
	"메뉴로 나가겠습니까?": "Return to the main menu?",
	"1-%d 클리어!\n%s": "STAGE 1-%d CLEAR!\n%s",
	"별 보상 +%d   (보유 %d)": "Stars Earned +%d   (Total: %d)",
	"먼저 캐릭터를 선택하세요.": "Choose a character first.",
	"아직 잠긴 스테이지입니다.": "This stage is still locked.",
	"게임 장면을 찾을 수 없습니다.\n%s": "The game scene could not be found.\n%s",
	"게임 장면을 불러올 수 없습니다.\n%s": "The game scene could not be loaded.\n%s",
	"%s의 %s 키를 누르세요.": "Press a new key for %s (%s).",
	"주": "primary",
	"보조": "secondary",
	"진행 데이터를 삭제하지 못했습니다: %s": "Progress could not be deleted: %s",
	"패시브를 초기화할 수 없습니다.": "Upgrades could not be reset.",
	"스테이지를 완료할 수 없습니다.": "The stage result could not be recorded.",
	"패시브를 강화할 수 없습니다.": "This upgrade could not be purchased.",
	"모든 키를 기본값으로 복원했습니다.": "All controls have been restored to their defaults.",

	# Character select and character profiles.
	"이미지와 다섯 능력치, 특수 스킬을 비교하세요": "Compare each character's stats and signature ability.",
	"공격속도": "ATK SPD",
	"이동속도": "MOVE SPD",
	"점프력": "Jump",
	"스태미나": "Stamina",
	"특수공격": "Special",
	"특수 · %s": "SPECIAL · %s",
	"특수 · 전력 질주": "SPECIAL · Full Sprint",
	"특수 · 가드 브레이크": "SPECIAL · Guard Break",
	"특수 · 전방 보호벽": "SPECIAL · Bulwark",
	"특수 · 중력 물길": "SPECIAL · Gravity Stream",
	"특수 · 대청소": "SPECIAL · Clean Sweep",
	"특수 · 성역의 가호": "SPECIAL · Sanctuary's Grace",
	"특수 · 정지 태엽": "SPECIAL · Time Lock",
	"특수 · 표창": "SPECIAL · Shuriken",
	"선택 완료": "CONFIRM",
	"뒤로": "BACK",
	"%s 선택": "SELECT %s",
	"이전": "PREVIOUS",
	"현재": "SELECTED",
	"다음": "NEXT",
	"일반인": "Rookie",
	"복서": "Boxer",
	"방패병": "Shield Guard",
	"소방관": "Firefighter",
	"청소부": "Custodian",
	"성녀": "Saintess",
	"시계공": "Clockmaker",
	"닌자": "Ninja",
	"0별": "0 Stars",
	"3별": "3 Stars",
	"6별": "6 Stars",
	"9별": "9 Stars",
	"12별": "12 Stars",
	"15별": "15 Stars",
	"전 스테이지 무피해": "Clear Every Stage Untouched",
	"목표: 별 15개 (선택 제한 없음)": "Goal: Earn 15 Stars (selection currently unrestricted)",
	"목표: 전 스테이지 무피해 (선택 제한 없음)": "Goal: Clear Every Stage Untouched (selection currently unrestricted)",
	"균형형": "All-Rounder",
	"정면 돌파형": "Close-Range Bruiser",
	"정면 생존형": "Defensive Vanguard",
	"낙하 경로 제어형": "Drop-Path Controller",
	"근거리 복구형": "Close-Range Cleaner",
	"성스러운 수호형": "Sacred Guardian",
	"시간 정지형": "Time Controller",
	"고속 원거리형": "High-Speed Ranged",
	"성실하지만 경험이 부족한 기준 캐릭터.": "A dependable newcomer with balanced fundamentals.",
	"짧은 거리에서 블록을 강하게 밀어내는 공격형.": "An aggressive fighter who drives blocks back at close range.",
	"이동하는 보호벽으로 한쪽 위험을 견디는 수호자.": "A steadfast guardian who blocks danger from one side.",
	"중력에 따라 흐르는 물길로 활성 블록의 착지 위치를 바꾼다.": "Redirects falling pieces with a gravity-fed stream.",
	"발밑의 노출된 고정 블록을 빠르게 정리하는 현장 전문가.": "A cleanup specialist who removes exposed blocks underfoot.",
	"찬란한 가호로 짧은 시간 빠르게 움직이고 다음 기믹이나 보스 공격을 버틴다.": "A sacred guardian who moves swiftly and wards off the next hazard or boss strike.",
	"황동 톱니 가방과 거대한 태엽 열쇠로 낙하 시간을 멈추는 괴짜 장인.": "An eccentric artisan who winds falling time to a halt.",
	"긴 스카프를 휘날리며 활성 블록을 원거리에서 조작하는 고속 숙련자.": "A swift expert who manipulates active pieces from afar.",
	"목제 연습봉": "Wooden Training Staff",
	"복싱 글러브": "Boxing Gloves",
	"원형 방패": "Round Shield",
	"소방 도끼 옆면": "Fire Axe",
	"빗자루": "Broom",
	"성휘 지팡이": "Radiant Staff",
	"태엽 열쇠 지팡이": "Winding-Key Staff",
	"단봉": "Short Baton",
	"전력 질주": "Full Sprint",
	"가드 브레이크": "Guard Break",
	"전방 보호벽": "Bulwark",
	"중력 물길": "Gravity Stream",
	"대청소": "Clean Sweep",
	"성역의 가호": "Sanctuary's Grace",
	"정지 태엽": "Time Lock",
	"표창": "Shuriken",
	"2초 동안 좌우 이동속도가 60% 증가한다.": "Gain 60% move speed for 2 seconds.",
	"2초간 좌우 이동속도가\n60% 증가한다.": "Gain 60% move speed\nfor 2 seconds.",
	"전방 블록을 가능한 거리만큼 최대 3칸 민다.": "Drive the block ahead up to 3 cells, stopping at obstacles.",
	"전방 블록을 최대 3칸\n밀어낸다.": "Drive the block ahead\nup to 3 cells.",
	"시전 방향 앞에 세로 3칸 보호벽을 2초 동안 유지한다.": "Raise a 3-cell barrier ahead for 2 seconds.",
	"전방에 3칸 보호벽을\n2초간 세운다.": "Raise a 3-cell barrier ahead\nfor 2 seconds.",
	"전방에 3셀 물길을 4초 만들고 자동 낙하마다 흐르는 방향으로 1칸 이동시킨다.": "Create a 3-cell stream for 4 seconds. Each automatic drop nudges the active piece 1 cell with the current.",
	"전방에 흐르는 물길을\n4초간 만든다.": "Create a forward-flowing stream\nfor 4 seconds.",
	"발밑과 좌우 한 칸의 노출된 고정 블록을 최대 3개 제거한다.": "Remove up to 3 exposed locked blocks beneath and beside you.",
	"발밑 주변 고정 블록을\n최대 3개 제거한다.": "Remove up to 3 locked blocks\naround your feet.",
	"3초 동안 이동속도 +20%, 노란 오라가 유지되는 동안 다음 기믹·보스 공격 1회 무효. 압착은 막지 못한다.": "Gain 20% move speed for 3 seconds and negate the next hazard or boss hit while the golden aura holds. Crushing damage bypasses the ward.",
	"3초간 이동속도 +20%,\n공격 1회를 무효화한다.": "+20% move speed for 3 seconds;\nnegate the next hit.",
	"활성 블록과 다음 가시·결박·씨앗 발동을 3초 동안 늦춘다.": "Freeze the active piece and delay the next thorn, bind, or seed trigger for 3 seconds.",
	"활성 블록과 다음 기믹을\n3초간 멈춘다.": "Freeze the active piece and\nnext hazard for 3 seconds.",
	"전방 6칸으로 표창을 던져 활성 블록 덩어리 전체를 정확히 1칸 민다. 고정 블록에는 막힌다.": "Throw a shuriken up to 6 cells, pushing the entire active piece exactly 1 cell. Locked blocks stop it.",
	"전방 표창으로 활성 블록을\n1칸 밀어낸다.": "Throw a shuriken to push\nthe active piece 1 cell.",

	# Upgrade shop.
	"공속": "Attack Speed",
	"이동": "Movement",
	"점프": "Jump",
	"특수스킬": "Special",
	"체력": "Vitality",
	"기본 공격과 회전킥의 재사용 대기시간이 줄어듭니다.": "Reduces the cooldown of basic attacks and Block Flip.",
	"좌우 이동 속도가 빨라집니다.": "Increases horizontal movement speed.",
	"점프 높이가 높아집니다.": "Increases jump height.",
	"벽에 매달릴 때 스태미나 소모량이 줄어듭니다.": "Reduces stamina drain while hanging from walls.",
	"특수 스킬의 재사용 대기시간이 줄어듭니다.": "Reduces signature ability cooldowns.",
	"레벨마다 캐릭터의 목숨이 1개 추가됩니다.": "Grants 1 additional life per level.",
	"현재 효과: 목숨 +%d · Lv. %d / %d": "Current: +%d Lives · Lv. %d / %d",
	"현재 효과: %s%d%% · Lv. %d / %d": "Current: %s%d%% · Lv. %d / %d",
	"최대 레벨": "MAX LEVEL",
	"다음 비용 ★ %d": "NEXT COST ★ %d",

	# Input actions and settings messages.
	"왼쪽 이동": "Move Left",
	"오른쪽 이동": "Move Right",
	"명상": "Meditate",
	"기본 밀치기": "Basic Push",
	"특수 스킬": "Signature Ability",
	"블록 플립": "Block Flip",
	"자력 재스폰": "Manual Respawn",
	"일시정지": "Pause",
	"다시 시작": "Restart",
	"미지정": "Unassigned",
	"알 수 없는 입력 동작입니다.": "Unknown input action.",
	"변경할 수 없는 키 슬롯입니다.": "This binding slot cannot be changed.",
	"주 키는 비워둘 수 없습니다.": "The primary binding cannot be empty.",
	"Esc는 메뉴 복귀 전용 키입니다.": "Esc is reserved for returning to the menu.",
	"%s 키는 이미 '%s'에 사용 중입니다.": "%s is already assigned to '%s'.",
	"%s 키가 변경되었습니다.": "%s binding updated.",
	"보조 키가 없는 동작입니다.": "This action has no secondary binding.",
	"%s 보조 키를 지웠습니다.": "Secondary binding cleared for %s.",
	"알 수 없는 패시브입니다.": "Unknown upgrade.",
	"이미 최대 레벨입니다.": "This upgrade is already maxed out.",
	"별이 부족합니다. 필요한 별: %d개": "Not enough stars. Required: %d",
	"패시브 강화를 저장하지 못했습니다: %s": "Could not save the upgrade: %s",
	"패시브 초기화를 저장하지 못했습니다: %s": "Could not save the upgrade reset: %s",
	"알 수 없는 스테이지입니다.": "Unknown stage.",
	"스테이지 클리어 별은 1개 이상이어야 합니다.": "A cleared stage must award at least 1 star.",
	"스테이지 결과를 저장하지 못했습니다: %s": "Could not save the stage result: %s",
	"설정 파일을 읽지 못했습니다: %s": "Could not read the settings file: %s",
	"저장된 키 설정에 중복이 있어 기본값으로 복원했습니다.": "Duplicate saved bindings were found, so controls were restored to defaults.",
	"설정을 저장하지 못했습니다: %s": "Could not save settings: %s",

	# Tutorial pages.
	"1. 이동과 점프": "1. MOVEMENT & JUMPING",
	"기본 이동부터 높이 조절 점프까지": "Master movement and variable-height jumps.",
	"좌우 이동": "MOVE LEFT & RIGHT",
	"[%s] 키로 블록 사이를 이동합니다.": "Use [%s] to move between blocks.",
	"[%s]를 짧게/길게 눌러 높이를 조절합니다.": "Tap or hold [%s] to control jump height.",
	"빠르게 놓기: 낮게": "Tap: Low",
	"유지: 높게": "Hold: High",
	"2. 블록 조작": "2. BLOCK CONTROL",
	"밀치기와 플립으로 길을 만드세요": "Push and flip blocks to open a path.",
	"1칸": "1 Cell",
	"준비": "Ready",
	"X를 누르면 전방 블록을 정확히 1칸 밀기": "Press X: push the block ahead 1 cell.",
	"캐릭터별 무기 모션만 다르고 결과는 동일": "Weapon animations vary; the effect is the same.",
	"90° 플립": "90° Flip",
	"지상·공중 모두 사용": "Works on ground or in midair.",
	"성공 뒤 2초, 실패 뒤 1초 대기": "Cooldown: 2s success · 1s failure.",
	"3. 매달리기와 벽 점프": "3. WALL GRAB & WALL JUMP",
	"화살표 순서대로 입력하면 더 높은 위치에 재매달립니다": "Follow the arrows to regrab the wall higher up.",
	"C 유지 중 ↑/↓로 벽 이동": "Hold C and use ↑/↓ to climb.",
	"벽 반대 방향으로 점프": "Jump away from the wall.",
	"원래 벽 방향으로 직접 조향": "Steer back toward the wall.",
	"%s를 유지하면 높은 위치에 다시 매달립니다.": "Keep holding %s to grab the wall higher up.",
	"%s를 놓은 뒤 0.15초 안에\n%s를 눌러도 벽 점프가 이어집니다.": "After releasing %s, press %s within 0.15s\nto continue into a wall jump.",
	"※ 오른쪽 벽에서는 좌우 방향이 반대입니다.": "Right wall: reverse directions.",
	"4. 명상과 시스템 키": "4. MEDITATION & SYSTEM KEYS",
	"낙하 블록의 흐름을 조절하고 언제든 다시 시작할 수 있습니다": "Control the pace of falling blocks and restart whenever needed.",
	"바닥에서 키 유지": "Hold the key while grounded.",
	"캐릭터 행동 정지": "Your character cannot act.",
	"블록 낙하·잠금 시간 ×2": "Piece fall and lock time ×2",
	"스태미나 회복 없음": "Stamina does not recover.",
	"키를 놓거나 발판을 잃으면 즉시 종료": "Ends if released or airborne.",
	"1초 유지: 목숨 -1 후 상단 재스폰": "Hold 1s: Spend 1 life to respawn.",
	"마지막 목숨이거나 안전한 칸이 없으면\n게임 오버입니다.": "You lose if it is your last life\nor no safe cell remains.",
	"착지 시 100 · 공중/벽 충전 없음": "Land: 100 · No air/wall charge",
	"5. 특수 키 모션": "5. SYSTEM ACTIONS",
	"게임 흐름을 멈추거나 다시 시작하고 안전하게 메뉴로 돌아가요": "Pause, restart, respawn, or return safely to the menu.",
	"다시 누르면 게임이 이어집니다.": "Press again to resume.",
	"즉시 재시작": "INSTANT RESTART",
	"보드·목숨을 처음부터 시작합니다.": "Reset the board and lives to their starting state.",
	"1초 유지": "Hold 1s",
	"목숨 3 → 2": "Lives 3 → 2",
	"목숨 3": "Lives 3",
	"게임 중 → 메뉴": "IN-GAME → MENU",
	"Esc를 눌러 메뉴 선택": "Press Esc to open the menu prompt.",
	"↑/↓ 선택 · Z 확인 · X 취소": "↑/↓ Select · Z Confirm · X Cancel",

	# In-game HUD and feedback.
	"삭제한 줄 %d": "LINES %d",
	"목숨: %d": "LIVES: %d",
	"자력 리스폰 준비 중 %d%%": "RESPAWN CHARGING %d%%",
	"일시정지\n\nP로 계속 · Esc로 메뉴": "PAUSED\n\nP Resume · Esc Menu",
	"게임 오버\n\nR 키로 다시 시작\nEsc 키로 메뉴": "GAME OVER\n\nR Restart\nEsc Menu",
	"%s 재사용 대기 중": "%s is on cooldown.",
	"지금은 특수 스킬을 사용할 수 없음": "Signature ability unavailable right now.",
	"지상에서만 사용 가능": "Can only be used while grounded.",
	"%s 발동": "%s activated!",
	"가드 브레이크: %d칸": "Guard Break: %d cells",
	"가드 브레이크 실패": "Guard Break failed.",
	"보호벽 생성 공간 부족": "Not enough room to raise the barrier.",
	"전방 보호벽 발동": "Bulwark raised!",
	"중력 물길 발동": "Gravity Stream activated!",
	"물길 생성 실패": "Could not create the stream.",
	"대청소: %d개 제거": "Clean Sweep: %d blocks removed",
	"대청소 대상 없음": "No blocks in range for Clean Sweep.",
	"성역의 가호: 3초 강화": "Sanctuary's Grace: empowered for 3s",
	"낙하 시간 3초 정지": "Falling time frozen for 3s.",
	"정지 태엽 실패": "Time Lock failed.",
	"표창 발사": "Shuriken thrown!",
	"성역의 가호: 기믹 무효": "Sanctuary's Grace negated the hazard!",
	"자력 재스폰: 목숨 -1": "Manual Respawn: -1 Life",
	"벽 점프": "Wall Jump",
	"보스 가시 피해! 목숨 -1": "Boss thorns hit! -1 Life",
	"%s: 1칸 밀치기": "%s: pushed 1 cell",
	"공격이 빗나감": "Attack missed.",
	"명상 ×2": "Meditation ×2",
	"명상 종료": "Meditation ended.",
	"지금은 블록 플립을 사용할 수 없음": "Block Flip unavailable right now.",
	"블록 플립 재사용 대기 중": "Block Flip is on cooldown.",
	"활성 블록에 닿지 않음": "No active block in range.",
	"공중 블록 플립 성공": "Midair Block Flip successful!",
	"회전 공간 부족": "Not enough room to flip the block.",
	"가시 회전킥 피해! 목숨 -1": "Thorn counterattack! -1 Life",
	"벽 점프 재매달리기": "Wall Regrab",
	"매달리기": "Wall Grab",
	"보드 이탈: 안전 위치 복귀": "Returned to a safe position.",
	"보호벽 방어": "Bulwark blocked the hit!",
	"압착 피해! 목숨 -1": "Crushed! -1 Life",
	"가시 공격 피해! 목숨 -1": "Thorn hit! -1 Life",
	"성역의 가호 방어": "Sanctuary's Grace blocked the hit!",
	"표창으로 활성 블록 밀치기 성공": "Shuriken pushed the active piece!",
	"표창이 막혔거나 활성 블록 공간 없음": "Shuriken blocked or no room to move the active piece.",
}

static var _english_translation: Translation
static var _korean_translation: Translation


static func install(language_code: String) -> void:
	if _english_translation == null:
		_english_translation = Translation.new()
		_english_translation.locale = ENGLISH
		for source: String in ENGLISH_MESSAGES:
			_english_translation.add_message(source, str(ENGLISH_MESSAGES[source]))
		TranslationServer.add_translation(_english_translation)
		_korean_translation = Translation.new()
		_korean_translation.locale = KOREAN
		for source: String in ENGLISH_MESSAGES:
			_korean_translation.add_message(source, source)
		TranslationServer.add_translation(_korean_translation)
	TranslationServer.set_locale(normalize_language(language_code))


static func normalize_language(language_code: String) -> String:
	var normalized: String = language_code.to_lower()
	if normalized.begins_with(KOREAN) or normalized.begins_with("zh"):
		return KOREAN
	return ENGLISH


static func translated(source: String) -> String:
	return TranslationServer.translate(source)
